name: Build and push docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        TAG=$(date +%s)
        docker build . --file Dockerfile --tag adamcathersides/slack-autoarchive:$TAG
        echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
        docker push adamcathersides/slack-autoarchive:$TAG
        docker tag adamcathersides/slack-autoarchive:$TAG adamcathersides/slack-autoarchive:latest
        docker push adamcathersides/slack-autoarchive:latest
